# -*- coding: utf-8 -*-
"""TF2.0 Text Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1spOPfwBOLLytXk46L8GoLTxBxp3ZIqVu
"""

import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = [
    "I like eggs and ham.",
    "I love chocolate and bunnies.",
    "I hate onions."
]

MAX_VOCAB_SIZE = 20000
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

print(sequences)

tokenizer.word_index

data = pad_sequences(sequences)
print(data)

MAX_SEQUENCE_LENGHT = 5
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGHT)
print(data)

data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGHT, padding='post')
print(data)

data = pad_sequences(sequences, maxlen=6)
print(data)

data = pad_sequences(sequences, maxlen=4)
print(data)

data = pad_sequences(sequences, maxlen=4, padding='post')
print(data)