# -*- coding: utf-8 -*-
"""TF2.0 Intro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mu6gQ9DV0I9wIlDOYt7mLP1isWlfgefF

# This is my title

This is regular text



```
# This is formatted as code
```
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10*np.pi, 1000)
y = np.sin(x)

plt.plot(x, y)